trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'aurelienadvanced/projet-jeu'

stages:
- stage: BuildImage
  displayName: 'Build Docker Image'
  jobs:        
    - job: BuildImageJob
      displayName: Build a docker image
      pool:
        name: Default
      steps:
      - script: |
          docker build -t $(imageName):$(tag) .
        displayName: 'Build Docker Image'
      
      - script: |
          docker login -u aurelienadvanced -p Aurelien20155?
          docker push $(imageName):$(tag)
        displayName: 'Push Docker Image to Docker Hub'