trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildImage
  displayName: 'Build Docker Image'
  jobs:        
    - deployment: DeployWebTest
      displayName: Build a docker image to on premise server
      environment:
        name: Docker
        resourceName: webserv
        resourceType: virtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                docker build -t feur/latest:$(Build.BuildId)

- stage: DeployToDevEnv
  displayName: 'Deploy to dev env'
  dependsOn: BuildImage
  jobs:        
    - deployment: DeployWebTest
      displayName: Deploy a docker image to on premise server
      environment:
        name: Docker
        resourceName: webserv
        resourceType: virtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                docker run  -p 8080:80 --name latest$(Build.BuildId) -d feur/latest:$(Build.BuildId)