trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'aurelienadvanced/projet-jeu'

stages:
- stage: TestUnit
  displayName: 'Run Unit Tests'
  jobs:
  - job: TestUnitJob
    displayName: Run unit tests
    pool:
      name: Default
    steps:
    - script: |
        go test ./...
      displayName: 'Run Go Unit Tests'
      
- stage: BuildImage
  displayName: 'Build Docker Image'
  jobs:        
    - job: BuildImageJob
      displayName: Build a docker image
      pool:
        name: Default
      steps:
      - script: |
          docker build -t $(imageName):$(tag) .
        displayName: 'Build Docker Image'
      
      - script: |
          docker login -u aurelienadvanced -p Aurelien20155?
          docker push $(imageName):$(tag)
        displayName: 'Push Docker Image to Docker Hub'