# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndDeploy
  displayName: 'Build and Deploy'
  jobs:
  - job: BuildAndDeployJob
    displayName: 'Build and Deploy Job'
    pool:
      vmImage: 'golang:alpine3.19'
    steps:
    - script: echo This is a placeholder build step.
      displayName: 'Placeholder Build Step'

- stage:
  displayName: 'Deploy to dev env'
  dependsOn: BuildAndDeploy
  jobs:        
    - deployment: DeployWebTest
      displayName: Deploy a docker image to on premise server
      environment:
        name: Docker
        resourceName: webserv
        resourceType: virtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                docker run  -p 8080:80 --name latest$(Build.BuildId) -d feur/latest:$(Build.BuildId)
