---
# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  name: Default

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11'
  GOPATH: '$(Agent.BuildDirectory)\gopath' # Go workspace path
  modulePath: '$(GOPATH)\src\github.com\$(Build.Repository.Name)' # Path to the module's code

steps:
- powershell: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)\pkg'
    mkdir -p '$(modulePath)'
    Copy-Item -Path $(Agent.BuildDirectory)\* -Destination $(modulePath) -Recurse
    Write-Host "##vso[task.prependpath]$(GOBIN)"
    Write-Host "##vso[task.prependpath]$(GOROOT)\bin"
  displayName: 'Set up the Go workspace'

- powershell: |
    go version
    go get -v -t -d ./...
    if (Test-Path Gopkg.toml) {
        (New-Object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/golang/dep/master/install.sh', 'dep-install.sh')
        .\dep-install.sh | Invoke-Expression
        dep ensure
    }
    go build -v .
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'
