trigger:
- main

pool:
  name: Default

variables:
  GOBIN: '$(GOPATH)/bin'
  GOROOT: '/usr/local/go' # Assurez-vous d'utiliser la version correcte de Go
  GOPATH: '$(Agent.BuildDirectory)/gopath'
  modulePath: '$(GOPATH)/src/github.com/$(Build.Repository.Name)'
  imageName: 'webserver-image:$(Build.BuildId)'

steps:
- powershell: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    Copy-Item -Path $(Agent.BuildDirectory)/* -Destination $(modulePath) -Recurse
    Write-Host "##vso[task.prependpath]$(GOBIN)"
    Write-Host "##vso[task.prependpath]$(GOROOT)/bin"
  displayName: 'Set up the Go workspace'

- powershell: |
    go version
    go get -v -t -d ./...
    go build -v .
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageName)
  displayName: 'Build Docker image'

- task: Docker@2
  inputs:
    command: 'push'
    repository: 'yourDockerHubUsername/yourRepository'
    tags: |
      $(imageName)
  displayName: 'Push Docker image'
